### ISSUE TITLE
Permission error on Android when entering strolling mode

### ISSUE THREAD

**Issue by carpenterd777** [Peer-Stevens/peer#38]
```
[Unhandled promise rejection: Error: Location provider is unavailable. Make sure that location services are enabled.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-location/build/Location.js:26:11 in getCurrentPositionAsync
at node_modules/expo-location/build/Location.js:25:7 in getCurrentPositionAsync
at src/components/NearbyPlaces/useLocation.ts:16:26 in <anonymous>
```

**Comment by carpenterd777** [comment]
Looks like this is still an open issue for expo
https://github.com/expo/expo/issues/14248

>Only workaround that's working for us is to use Location.getLastKnownPositionAsync();. You can either choose prefer last known >or use it as fallback, up to you. This has significantly reduced error rates we are seeing in our application.

We can try using this as a fallback

**Comment by carpenterd777** [comment]
https://stackoverflow.com/questions/66385839/expo-location-error-unhandled-promise-rejection-error-not-authorized-to-use-b

Its possible that I'll need to actually build the app in order to test location services.
